local_costmap:
  global_frame: map
  robot_base_frame: body
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  transform_tolerance: 0.5
  plugins:
    - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    footprint_clearing_enabled: true
    observation_sources: depth_points
    depth_points:
      data_type: PointCloud2
      topic: /rtabmap/local_grid_obstacle
      marking: true
      clearing: true
      min_obstacle_height: 0.01
      max_obstacle_height: 2.0

  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
