#!/usr/bin/env python

import sys
import yaml
from rbd_movo_motor_skills.motion_planning.framework import Verifier

class ARTagPoseVerifier(Verifier):
    """
    Assumes the AR Tag detector node is running.
    You may want to start the relevant system launch
    file first.
    """
    def __init__(self, name, cue, rate=10):
        super(ARTagPoseVerifier, self).__init__(name, cue, rate=rate)

    def _verify(self):
        return Verifier.NOT_DONE

if __name__ == "__main__":
    node_name = sys.argv[1]
    cue = yaml.load(sys.argv[2])
    ARTagPoseVerifier(node_name, cue)
