#!/usr/bin/env python

import sys
import rospy
import yaml

from control_msgs.msg import (
    GripperCommandActionResult,
)

from rbd_movo_motor_skills.motion_planning.framework import Verifier
from rbd_movo_motor_skills.config import GRIPPER_POSITION_MAX
from rbd_movo_motor_skills.utils.ros_utils import remap


class GripperCommandVerifier(Verifier):
    """
    Gripper state verifier. Although the gripper states
    are published under /movo/left_gripper/joint_states,
    the values in the "position" field of those messages
    do not match the value of "position" in the command,
    sent to the Gripper Action Server. Therefore, it is
    quite challenging to tell whether a gripper goal
    state is reached.

    Experimentally, I have observed:
    - When the gripper is fully open, the joint_state
      position reading is 0.002549 for finger1, 0.0016998
      for fingers 2 and 3.

    - When fully closed, the value is about 0.890716
      for all fingers.

    - When half open, the value is about 0.515
      for all fingers.

    It is a little tricky to check for these values. Instead,
    the Action Server publishes feedback to the Action Client,
    at '/movo/left_gripper_controller/gripper_cmd/feedback'
    If the goal is successful, then the last feedback
    will have a 'reached_goal' field to be True.
    """
    def __init__(self, name, cue, rate=10):
        super(GripperCommandVerifier, self).__init__(name, cue, rate=rate)
        side = cue['args']['side']
        self._spec_position = cue['args']['position']
        rospy.Subscriber("/movo/{}_gripper_controller/gripper_cmd/result".format(side),
                         GripperCommandActionResult, self._callback)

    def _callback(self, m):
        if m.result.reached_goal:
            position_in_spec = remap(m.result.position, 0., GRIPPER_POSITION_MAX, 0., 1.)
            self.message = "ok"
            self.status = Verifier.DONE
            return

        self.message = "Gripper command goal not reached"
        self.status = Verifier.NOT_DONE

if __name__ == "__main__":
    node_name = sys.argv[1]
    cue = yaml.load(sys.argv[2])
    verifier = GripperCommandVerifier(node_name, cue, rate=10)
    verifier.run()
